# Generated by Django 3.1.5 on 2021-01-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FinEdu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_text',
        ),
    ]
